### PR TITLE
Yet another fix of visual assist color scheme

### PR DESCRIPTION
**Pull request by DecoyRS**

### CODE REVIEW

**Comment by DecoyRS** [comment]
I can't quite understand how IDE will change the way files are stored on Github...
The reason why I've sorted them this way to be able to compare vax dark with vax light easier, to find things that are added to one scheme and were missing in another one. And in case there will be other coloring for symbols added in the future e.g. new kind of UE macros that have a specific coloring that will differ from all the other ones.

**Comment by homatyano** [comment]
XML files are not quite suitable to compare using a plain text diff. So I have implemented an utility which sorts these files uniformly. Hopefully this is going to help with that.

**Comment by DecoyRS** [comment]
Unfortunately, alphanumerical sorting doesn't bring any value in my case.
I've specifically separated with comments values that are unique for Dark (or Light) scheme so that the next time someone would look into it, this person won't be trying to add or search for this value  marked as "Unique".

**Comment by homatyano** [comment]
Hm, I don't quite get what you call 'Unique VAX light'. Do you mean these keys is the difference between VAX Light and say ReSharper Light (or Visual Studio Light), and everything else is the same between them?

If this is indeed what you intented, you should remove all keys which are not 'unique' for VAX Light, and then set ReSharper Light (or whatever) as the parent scheme. Since the entire content of the file is going to be 'unique' now, you won't need to manually mark a part of the file as 'unique' and expect that others will understand and follow your intention.

**Pull request merged**
