### PR TITLE
Override icon in gutter for setting next statement while debugging

### PR DESCRIPTION
**Pull request by LeoMash**

### CODE REVIEW

**Comment by homatyano** [comment]
The path for the icon to be substituted should start with a '/'.

**Comment by homatyano** [comment]
The dark themes should substitute 'nextStatement_dark.svg'

**Comment by homatyano** [comment]
It's OK to substitute the icon for the themes 'VS', 'ReSharper', and 'VisualAssist'. But 'Rider' and 'RiderMelon' should keep using the default platform icon.

**Comment by LeoMash** [comment]
> The path for the icon to be substituted should start with a '/'.

it's the path in autogenerated AllIcons.java and substitution doesn't work if I put path starting with '/'. 
Either schema is not correct or icons synchronizer in idea.

**Comment by LeoMash** [comment]
> The dark themes should substitute 'nextStatement_dark.svg'

Actually it also doesn't work. Only original raw icon name ('nextStatement.svg') is passed to theme substitution code even for dark themes. Seems that all postfixes (_dark) are applied afterwards.

**Comment by homatyano** [comment]
I have just checked if the slash is required and indeed it is. If the path to the icon doesn't start with a forward slash, a dot is displayed instead of either the old or the new icon. It doesn't make sense to me but that's how it works at the moment.

**Pull request closed without merging**
